### ISSUE TITLE
Claim for incorrect results [proved wrong]

### ISSUE THREAD

**Issue by akito047** [YingYuChen97/CSCA#3]
I am sorry to say this, but your code is buggy. You are evaluating the same support set you are building prototypes on. 
```
               for j in range(opt.way):
                    output = model[i](mtest_data).squeeze(-1).squeeze(-1)
                    sim_matrix[j] = cos(output[i * opt.query:(i+1) * opt.query],prototypes[j]).cpu().data.numpy()
                
                pred = np.argmax(sim_matrix,axis=0)
                correct += np.count_nonzero(pred==i)
```

**Comment by YingYuChen97** [comment]
The prototypes are built with support set **mtrain_data** in lines 93~96.

```
output = model[i](mtest_data).squeeze(-1).squeeze(-1)
```
Here **mtest_data** is tested.
I don't really understand your problem, please describe more.

**Comment by akito047** [comment]
I am sorry. Your naming convection `mtrain_data` and `mtest_data` confused me. Looks like the bug I thought was not there in the code. Your approach is just so simple that it is unbelievable that it works so well.
